tap "anomalyco/tap", trusted: true
tap "charmbracelet/tap", trusted: true
tap "codecrafters-io/tap", trusted: true
tap "homebrew/services"
tap "jesseduffield/lazydocker", trusted: true
tap "jesseduffield/lazygit", trusted: true
tap "oven-sh/bun", trusted: true
# Automate deployment, configuration, and upgrading
brew "ansible"
# Checks ansible playbooks for practices and behaviour
brew "ansible-lint"
# Embeddable SQL OLAP Database Management System
brew "duckdb"
brew "elixir"
# Simple, fast and user-friendly alternative to find
brew "fd"
brew "flyctl"
# Command-line fuzzy finder written in Go
brew "fzf"
brew "gh"
brew "git"
brew "gleam"
brew "glow"
brew "go"
# General purpose AT Protocol CLI in Go
brew "goat"
# Fast linters runner for Go
brew "golangci-lint"
brew "jq"
brew "k9s"
brew "kubectx"
brew "kubernetes-cli"
brew "lazygit"
# Like sed, awk, cut, join & sort for name-indexed data such as CSV
brew "miller"
brew "mongosh"
brew "neovim"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
brew "postgresql@18", restart_service: :changed
brew "pre-commit"
brew "rgbds"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Readline wrapper: adds readline support to tools that lack it
brew "rlwrap"
brew "starship"
brew "stow"
brew "swi-prolog"
brew "tmux"
brew "tmuxinator"
# Parser generator tool
brew "tree-sitter-cli"
# Internet file retriever
brew "wget"
brew "yazi"
brew "anomalyco/tap/opencode", trusted: true
brew "codecrafters-io/tap/codecrafters"
brew "jesseduffield/lazydocker/lazydocker", trusted: true
brew "oven-sh/bun/bun", trusted: true
cask "1password-cli"
cask "bruno"
cask "claude-code@latest"
cask "ghostty"
go "golang.org/x/tools/cmd/goimports"
go "github.com/BurntSushi/toml/cmd/tomlv"
