name: production-ready-serverless-workshop
root: ~/Documents/production-ready-serverless-workshop/
windows:
  - editor:
      layout: main-vertical
      panes:
        - nvim .
        -
  - git: lazygit
  - prompt:
