palette = "dracula"
command_timeout = 3000
format = """
$directory\
$git_branch\
$git_state\
$git_status\
$elixir\
$golang\
$nodejs\
$python\
$rust\
$kubernetes\
$aws\
$gcloud\
$cmd_duration\
$line_break\
$character\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[character]
success_symbol = "[[](yellow) ](subtext0)"
error_symbol = "[[󱇎](red) ](subtext0)"

[directory]
truncation_length = 4
truncation_symbol = ".../"
style = "bold pink"
format = "[$path ]($style)"

[aws]
symbol = "󰸏"
style = "fg:orange"
format = '[ $symbol $profile ]($style)'

[cmd_duration]
format = "[ $duration]($style) "
style = "subtext0"

[elixir]
symbol = " "
style = "fg:purple"
format = '[ $symbol ($version) ]($style)'

[gcloud]
symbol = "󱇶"
style = "fg:cyan"
format = "[ $symbol ($project) ]($style)"

[git_branch]
symbol = ""
style = "fg:foreground"
format = '[ $symbol $branch ]($style)'

[git_status]
format = "[ [(*$conflicted$untracked$modified$staged$renamed$deleted) ](218)($ahead_behind$stashed)]($style)"
style = "fg:foreground"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "fg:foreground"

[golang]
symbol = " "
style = "fg:cyan"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
symbol = "󱃾"
style = "fg:cyan"
format = '[ $symbol $context( \($namespace\)) ]($style)'
disabled = false

[nodejs]
symbol = ""
style = "fg:green"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "fg:yellow"
format = '[ $symbol ($version) \(($virtualenv)\) ]($style)'

[rust]
symbol = ""
style = "fg:orange"
format = '[ $symbol ($version) ]($style)'

[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
selection = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"
