palette = "catppuccin_macchiato"
command_timeout = 3000
format = """
$directory\
$git_branch\
$git_state\
$git_status\
$elixir\
$golang\
$nodejs\
$python\
$rust\
$kubernetes\
$aws\
$gcloud\
$cmd_duration\
$line_break\
$character\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[character]
success_symbol = "[[](yellow) ](subtext0)"
error_symbol = "[[󱇎](red) ](subtext0)"

[directory]
truncation_length = 4
truncation_symbol = ".../"
style = "bold lavender"
format = "[$path ]($style)"

[aws]
symbol = "󰸏"
style = "fg:peach"
format = '[ $symbol $profile ]($style)'

[cmd_duration]
format = "[ $duration]($style) "
style = "subtext0"

[elixir]
symbol = " "
style = "fg:mauve"
format = '[ $symbol ($version) ]($style)'

[gcloud]
symbol = "󱇶"
style = "fg:sapphire"
format = "[ $symbol ($project) ]($style)"

[git_branch]
symbol = ""
style = "fg:rosewater"
format = '[ $symbol $branch ]($style)'

[git_status]
format = "[ [(*$conflicted$untracked$modified$staged$renamed$deleted) ](218)($ahead_behind$stashed)]($style)"
style = "fg:flamingo"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "fg:flamingo"

[golang]
symbol = " "
style = "fg:sky"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
symbol="󱃾"
style="fg:lavender"
format='[ $symbol $context( \($namespace\)) ]($style)'
disabled = false

[nodejs]
symbol = ""
style = "fg:green"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style="fg:yellow"
format = '[ $symbol ($version) \(($virtualenv)\) ]($style)'

[rust]
symbol = ""
style = "fg:maroon"
format = '[ $symbol ($version) ]($style)'

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
