palette = "tokyonight"
command_timeout = 3000
format = """
$directory\
$git_branch\
$git_state\
$git_status\
$elixir\
$golang\
$nodejs\
$python\
$rust\
$kubernetes\
$aws\
$gcloud\
$cmd_duration\
$line_break\
$character\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[character]
success_symbol = "[[](yellow) ](subtext0)"
error_symbol = "[[󱇎](red) ](subtext0)"

[directory]
truncation_length = 4
truncation_symbol = ".../"
style = "bold magenta"
format = "[$path ]($style)"

[aws]
symbol = "󰸏"
style = "fg:red"
format = '[ $symbol $profile ]($style)'

[cmd_duration]
format = "[ $duration]($style) "
style = "subtext0"

[elixir]
symbol = " "
style = "fg:magenta"
format = '[ $symbol ($version) ]($style)'

[gcloud]
symbol = "󱇶"
style = "fg:cyan"
format = "[ $symbol ($project) ]($style)"

[git_branch]
symbol = ""
style = "fg:foreground"
format = '[ $symbol $branch ]($style)'

[git_status]
format = "[ [(*$conflicted$untracked$modified$staged$renamed$deleted) ](218)($ahead_behind$stashed)]($style)"
style = "fg:foreground"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "fg:foreground"

[golang]
symbol = " "
style = "fg:cyan"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
symbol = "󱃾"
style = "fg:cyan"
format = '[ $symbol $context( \($namespace\)) ]($style)'
disabled = false

[nodejs]
symbol = ""
style = "fg:green"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "fg:yellow"
format = '[ $symbol ($version) \(($virtualenv)\) ]($style)'

[rust]
symbol = ""
style = "fg:red"
format = '[ $symbol ($version) ]($style)'

[palettes.tokyonight]
black = '#444a73'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#c8d3f5'
