format = """
[](#c4a7e7)\
$directory\
[](bg:#eb6f92 fg:#c4a7e7)\
$git_branch\
$git_status\
[](fg:#eb6f92 bg:#ea9a97)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$nodejs\
$python\
$rust\
[](fg:#ea9a97 bg:#3e8fb0)\
$kubernetes\
[](fg:#3e8fb0 bg:#f6c177)\
$aws\
[](fg:#f6c177 bg:#9ccfd8)\
$gcloud\
[ ](#9ccfd8)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[directory]
style = "bg:#c4a7e7 fg:#232136"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[aws]
symbol = "󰸏"
style = "bg:#f6c177 fg:#232136"
format = '[ $symbol $profile ]($style)'

[c]
symbol = " "
style = "bg:#ea9a97 fg:#232136"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:#ea9a97 fg:#232136"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#ea9a97 fg:#232136"
format = '[ $symbol ($version) ]($style)'

[gcloud]
symbol = "󱇶"
style = "bg:#9ccfd8 fg:#232136"
format = "[ $symbol ($project) ]($style)"

[git_branch]
symbol = ""
style = "bg:#eb6f92 fg:#232136"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#eb6f92 fg:#232136"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#ea9a97 fg:#232136"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#ea9a97 fg:#232136"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
symbol="󱃾"
style="bg:#3e8fb0 fg:#232136"
format='[ $symbol $context( \($namespace\)) ]($style)'
disabled = false

[nodejs]
symbol = ""
style = "bg:#ea9a97 fg:#232136"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style="bg:#ea9a97 fg:#232136"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#ea9a97 fg:#232136"
format = '[ $symbol ($version) ]($style)'
