return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "comment",
      "css",
      "dockerfile",
      "elixir",
      "go",
      "gomod",
      "html",
      "htmldjango",
      "javascript",
      "jsdoc",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "mermaid",
      "python",
      "regex",
      "rust",
      "scss",
      "svelte",
      "toml",
      "tsx",
      "typescript",
      "vue",
      "yaml",
    },
  },
}
